# Exported from Render on 2025-06-13T06:13:59Z
services:
- type: web
  name: visitorServer
  runtime: docker
  repo: https://github.com/Rizwank123/visitorServer
  plan: free
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
version: "1"
