services:
  - type: web
    name: visitorServer
    runtime: docker
    repo: https://github.com/Rizwank123/visitorServer
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
    envVars:
      - key: APP_ENV_FILE
        value: .env
